### ISSUE TITLE
[FEATURE]  Improve profile API and UI

### ISSUE THREAD

**Issue by DebadityaPal** [hs2361/horario#3]
Currently, we only store the username and password, It would be better if we could store some more basic details like birthdays or a small bio.
The profile page would also need to be updated accordingly.

**Comment by AlecsisDuarte** [comment]
I'm planning to picking this one up, if that's okay!

Just some questions before doing so. I noticed that currently you leverage Firebase's User Authorization in order to store current user data, but that won't allow adding more info (e.g., Birthday, Bio). I'm planning to store that information in the Firestone instead.

Also should the Sing-up form, have this other parameters attributes? Or just at the profile screen?

**Comment by DebadityaPal** [comment]
Ideally, we would have the fields in the signup form as well.
I am assigning this issue to you, feel free to ping me if you need any help.
